# CoreTally configuration
rates:
  cpu_rate: 0.05
  gpu_rate: 0.50
  mem_rate: 0.01

# sacct filters and scope; adjust to your cluster
sacct_extra_args:
  - --clusters=merced
  - --accounts=pi_%
  - --partition=cpu,gpu
  - --state=COMPLETED,FAILED,TIMEOUT

# Optional SMTP for mailout()
smtp:
  host: smtp.example.edu
  port: 587
  starttls: true
  username: noreply@example.edu
  password: ""
  from_addr: noreply@example.edu
  finance_to: ["finance@example.edu"]

# Optional OIDC (CILogon) for API
oidc:
  client_id: ""
  client_secret: ""
  redirect_uri: "https://your-host.example.edu/callback"
  allowed_domains: ["example.edu"]
